### ISSUE TITLE
Critical Bug Report: Duplicate Email Sign-Up with Google and Manual Registration

### ISSUE THREAD

**Issue by meeeeet** [neeramrutia/nextjs_project_manager#1]
I have identified a critical issue on your website pertaining to the registration process. The problem arises when a user attempts to sign up using both Google authentication and manual email registration with the same email address. Surprisingly, the system allows the creation of two distinct accounts instead of preventing duplicate registrations. This behavior introduces a potential risk of data inconsistency and security vulnerabilities.

To replicate the issue, follow these steps: first, sign up with Google using a specific email address; then, log out and attempt to sign up again, this time opting for manual email registration with the same email address. The expected behavior should involve the system recognizing that the email address is already associated with an account, prompting the user to log in or preventing the creation of a new account with the same email.

The actual behavior, however, permits the user to establish two separate accounts with identical email addresses, which raises concerns about data integrity and poses a security threat. This bug warrants urgent attention and resolution to mitigate potential risks associated with user data and system security.

For further context, please note the environment in which this bug was identified, including the browser, operating system, and device used. Thank you for promptly addressing this critical issue.

**Comment by neeramrutia** [comment]
I am pleased to inform you that we have implemented a fix to address this issue. The system now correctly recognizes when an email address is already associated with an account during the manual email registration process, preventing the creation of duplicate accounts.
